language: ruby
sudo: false
rvm:
    - 2.1

before_script:
    - nvm use 0.12
    - npm install
    - ./node_modules/.bin/bower install

script:
    - ./node_modules/.bin/gulp dist
    - bundle exec htmlproof dist
