# Site settings
title: Matthew Loberg
tagline: Software Engineer
description: "Software Engineer from Minnesota"
url: "http://mlo.io"
baseurl: ""

author:
  name: Matthew Loberg
  picture: /assets/img/profile3.jpg
  email: m@mloberg.com
  twitter: mloberg

  social:
    - name: Twitter
      icon: twitter-square
      url: "https://twitter.com/mloberg"
    - name: Github
      icon: github
      url: "https://github.com/mloberg"
    - name: Instagram
      icon: instagram
      url: "https://www.instagram.com/mloberg/"
    # google:          _number_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # soundcloud:      _username_
    # lastfm:          _username_
    # flickr:          _string_@_string_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # linkedin:        _firstname_-_lastname_-_string_
    # paypal:          _username_

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

navigation:
  - title: About
    url: /about.html
    internal: true
  - title: Archive
    url: /archive.html
    internal: true

google_analytics_id: UA-9585810-14

# Build settings
source: site
destination: build
permalink: /blog/:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
timezone: America/Chicago

paginate: 5
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: '/category/:name/'

# Jekyll SEO
twitter:
  username: mloberg

social:
  name: Matthew Loberg
  links:
    - https://twitter.com/mloberg
    - https://github.com/mloberg
    - https://www.instagram.com/mloberg/

assets: site/assets/manifest.json
