# Site settings
title: Matthew Loberg
email: m@mloberg.com
description: "Web developer from Minnesota"
baseurl: ""
url: "http://mlo.io"

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      header: background.jpg

# Build settings
source: site
destination: build
permalink: /blog/:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
