# Site settings
title: Matt Loberg
description: >
  Principal Software Engineer specializing in Open Source technologies and DevOps.
baseurl: ""
url: "https://mlo.io"

icons:
  - href: https://twitter.com/mloberg
    icon: fab fa-twitter
    label: Follow me on Twitter
  - href: https://github.com/mloberg
    icon: fab fa-github
    label: View my GitHub profile
  - href: https://mlo.io/feed.xml
    icon: fas fa-rss
    label: RSS Feed

defaults:
  - scope:
      path: ""
    values:
      image: /images/twitter.png
      hero:
        name: main
        photographer: Daniel Leone
        link: https://unsplash.com/photos/g30P1zcOzXo

permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled: all
  layout: archive
  layouts:
    category: category
    tag: category
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# Jekyll SEO
logo: /images/profile.jpg

twitter:
  username: mloberg

social:
  name: Matt Loberg
  links:
    - https://twitter.com/mloberg
    - https://github.com/mloberg
    - https://www.instagram.com/mloberg

algolia:
  application_id: PRNXO4ZLOA
  index_name: jekyll
  search_only_api_key: 9bda0d4302c544799c7025e310ffebd1

# Build settings
timezone: America/Chicago
source: src
destination: dist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  startings: [html, head, body]

exclude:
  - assets/entrypoints.json
  - assets/manifest.json
