# Site settings
title: Matthew Loberg
email: m@mloberg.com
description: "Web developer from Minnesota"
baseurl: ""
url: "http://mlo.io"

# Build settings
source: site
destination: dist
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
highlighter: pygments

gems:
  - jekyll-sitemap
