# Site settings
title: Matthew Loberg
description: >
  Principal Software Engineer specializing in Open Source technologies and DevOps.
baseurl: ""
url: "http://mlo.io"

# Theme settings
theme: jekyll-theme-strata
show_excerpts: true
# date_format: "%b %-d, %Y"

disqus:
  shortname: mattwritescode

twitter_username: mloberg
github_username: mloberg
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: mloberg
linkedin_username: ~
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
rss: true

permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# Jekyll SEO
logo: /assets/images/profile.jpg

twitter:
  username: mloberg

social:
  name: Matthew Loberg
  links:
    - https://twitter.com/mloberg
    - https://github.com/mloberg
    - https://www.instagram.com/mloberg

# Build settings
timezone: America/Chicago
source: src
destination: dist
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
