version: '3.6'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve
    volumes:
      - ./vendor/bundle:/usr/local/bundle
      - .:/srv/jekyll:cached
    ports:
      - 4000:4000
  assets:
    image: node:10
    command: sh -c "npm install && npm run watch"
    working_dir: /app
    volumes:
      - .:/app
