name: Publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: npm ci
      - run: npm run lint
      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - run: bundle exec htmlproofer ./dist --disable-external
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: dist
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mloberg
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
